version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: study_swamp_db
      POSTGRES_USER: hero
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "
        python manage.py migrate && 
        python manage.py loaddata user.json &&
        python manage.py loaddata location.json &&
        python manage.py loaddata group.json &&
        python manage.py loaddata member.json &&
        python manage.py loaddata meeting.json &&
        python manage.py loaddata attendee.json &&
        python manage.py loaddata award.json &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
