# Generated by Django 5.2.1 on 2025-06-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Swamp_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.TextField(choices=[('MAS', 'MAS'), ('CEN', 'CEN'), ('COP', 'COP')], default='MAS'),
        ),
    ]
