# Generated by Django 5.2.1 on 2025-06-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Swamp_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Admin')], default=2),
        ),
    ]
