# Generated by Django 5.2.1 on 2025-06-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Swamp_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
