# Generated by Django 5.2.1 on 2025-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Swamp_API', '0002_user_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='rsvp',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Declined')]),
        ),
    ]
