# Generated by Django 5.2.1 on 2025-06-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Swamp_API', '0002_group_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='class_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
