# Generated by Django 5.2.1 on 2025-06-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Swamp_API', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='STUDENT'),
        ),
    ]
