# Generated by Django 5.2.1 on 2025-06-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Swamp_API', '0003_group_class_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='meeting',
            new_name='meeting_id',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='rsvp',
            new_name='rsvp_type',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='groupcomment',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='groupcomment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='location',
            new_name='location_id',
        ),
        migrations.RenameField(
            model_name='meetingcomment',
            old_name='meeting',
            new_name='meeting_id',
        ),
        migrations.RenameField(
            model_name='meetingcomment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user',
            new_name='user_id',
        ),
    ]
