# Generated by Django 5.2.1 on 2025-06-25 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Swamp_API', '0004_rename_meeting_attendee_meeting_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='meeting_id',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='award',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='groupcomment',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='groupcomment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='meetingcomment',
            old_name='meeting_id',
            new_name='meeting',
        ),
        migrations.RenameField(
            model_name='meetingcomment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='user',
        ),
    ]
