# Generated by Django 5.2.1 on 2025-06-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_Swamp_API', '0005_rename_meeting_id_attendee_meeting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='Study_Swamp_API.group'),
        ),
    ]
