name: Pytest Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: hero
          POSTGRES_PASSWORD: password
          POSTGRES_DB: study_swamp_db
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        python-version: ["3.13.3"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .
        continue-on-error: true
      - name: Run Migrations
        run: |
          MAX_TRIES=30
          COUNT=0
          until pg_isready -h db -p 5432; do
            COUNT=$((COUNT+1))
            if [ $COUNT -ge $MAX_TRIES ]; then
              echo "Postgres did not become ready in time."
              exit 1
            fi
            echo "Waiting for postgres..."
            sleep 5
          done
          python3 manage.py migrate
      - name: Test with Pytest
        run: |
          pytest -s